name: A TO A:GH_PAGES
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          cache: npm
      - name: Build and Deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: kazettique/vuepress-poc
          # TARGET_BRANCH: gh_pages
          BUILD_SCRIPT: npm i && npm run build
          BUILD_DIR: src/.vuepress/dist/
